import streamlit as st
import random
import string
from supabase import create_client, Client

# Initialize Supabase Client
url = st.secrets["supabase"]["url"]
key = st.secrets["supabase"]["key"]
supabase: Client = create_client(url, key)

class Bank:
    @classmethod
    def init_db(cls):
        """
        Supabase tables should be created via the Dashboard SQL Editor.
        This method serves as a schema reference.
        SCHEMA:
        create table public.users (
          id bigint generated by default as identity not null,
          created_at timestamp with time zone not null default now(),
          name text not null,
          age integer not null,
          email text not null,
          pin integer not null,
          account_number text not null,
          balance bigint null default 0,
          constraint users_pkey primary key (id),
          constraint users_account_number_key unique (account_number)
        ) TABLESPACE pg_default;
        """
        pass

    @classmethod
    def generate_account_number(cls):
        chars = random.choices(string.ascii_letters, k=3) + \
                random.choices(string.digits, k=3) + \
                random.choices("!@#$%^&*", k=1)
        random.shuffle(chars)
        return ''.join(chars)

    @classmethod
    def create_account(cls, name, age, email, pin):
        if age < 18 or len(str(pin)) != 4:
            return None, "Age must be 18+ and PIN should be 4 digits"
        
        acc_no = cls.generate_account_number()
        
        try:
            user_data = {
                "account_number": acc_no,
                "name": name,
                "age": age,
                "email": email,
                "pin": int(pin),
                "balance": 0
            }
            response = supabase.table("users").insert(user_data).execute()
            
            # Check for success (response.data should be a list with the inserted row)
            if response.data:
                # Map back to app structure
                user = response.data[0]
                user['accountNo.'] = user['account_number']
                return user, "Account created successfully"
            else:
                return None, "Failed to create account (No data returned)"
                
        except Exception as e:
            return None, f"Error: {e}"

    @classmethod
    def find_user(cls, acc_no, pin):
        try:
            response = supabase.table("users").select("*") \
                .eq("account_number", acc_no) \
                .eq("pin", int(pin)) \
                .execute()
            
            if response.data:
                user = response.data[0]
                user['accountNo.'] = user['account_number']
                return user
            return None
        except Exception as e:
            print(f"Supabase Error: {e}")
            return None

    @classmethod
    def deposit(cls, acc_no, pin, amount):
        # Placeholder for Story S4
        return False, "Deposit feature currently under maintenance (Migration to Supabase)"

    @classmethod
    def withdraw(cls, acc_no, pin, amount):
        # Placeholder for Story S5
        return False, "Withdrawal feature currently under maintenance (Migration to Supabase)"

    @classmethod
    def update_user(cls, acc_no, pin, name=None, email=None, new_pin=None):
        # Placeholder for Story S7
        return False, "Update feature currently under maintenance (Migration to Supabase)"

    @classmethod
    def delete_user(cls, acc_no, pin):
        # Placeholder for Story S10
        return False, "Delete feature currently under maintenance (Migration to Supabase)"

